# Generated by Django 4.2 on 2024-03-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'content')},
        ),
    ]
