# Generated by Django 4.2 on 2024-03-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_title_post_posts_title_c84406_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ['title']},
        ),
    ]
